# -*- coding: utf-8 -*-
"""Heart_Disease_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uovPz8VGghaA4-XUKicFfHk3gExfcjCn

## **Heart Disease Exploratory Data Analysis**

### **1. Pendahuluan**
Penyakit jantung merupakan salah satu penyebab utama kematian di dunia.
Dengan memanfaatkan data kesehatan pasien, analisis data dapat digunakan
untuk mengidentifikasi pola dan faktor risiko yang berkaitan dengan penyakit jantung.

Proyek ini bertujuan untuk melakukan exploratory data analysis (EDA)
terhadap dataset penyakit jantung guna memahami hubungan antara
faktor demografis dan klinis dengan kondisi penyakit jantung.

### **2. Dataset dan Tools**

### Dataset
Dataset yang digunakan adalah Heart Disease Prediction Dataset yang berisi
informasi demografis dan klinis pasien, seperti usia, jenis kelamin,
kolesterol, tekanan darah, dan detak jantung maksimum.

### Tools
- Python
- Google Colab
- Pandas
- Matplotlib
- Seaborn

**Load Dataset**
"""

import pandas as pd

df = pd.read_csv("Heart_Disease_Prediction.csv")
df.head()

"""### **3. Data Understanding**
Tahap ini bertujuan untuk memahami struktur dataset,
termasuk jumlah data, nama kolom, dan tipe data.

**Struktur Dataset**
"""

df.info()

"""**Nama Kolom**"""

df.columns

"""### **4. Exploratory Data Analysis**

##### **4.1. Distribusi Penyakit Jantung**
Analisis ini bertujuan untuk melihat proporsi pasien
yang mengalami dan tidak mengalami penyakit jantung.
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='Heart Disease', data=df)
plt.title('Distribusi Pasien Penyakit Jantung')
plt.xlabel('Kondisi')
plt.ylabel('Jumlah Pasien')
plt.show()

"""##### **4.2. Usia dan Penyakit Jantung**
Analisis ini membandingkan distribusi usia pasien
berdasarkan kondisi penyakit jantung.

"""

plt.figure(figsize=(8,5))
sns.boxplot(x='Heart Disease', y='Age', data=df)
plt.title('Distribusi Usia Berdasarkan Kondisi Penyakit Jantung')
plt.xlabel('Kondisi Penyakit Jantung')
plt.ylabel('Usia')
plt.show()
df.groupby('Heart Disease')['Age'].mean()

"""##### **4.3. Jenis Kelamin dan Penyakit Jantung**
Analisis ini bertujuan untuk melihat perbedaan proporsi
penyakit jantung berdasarkan jenis kelamin.

"""

plt.figure(figsize=(7,5))
sns.countplot(x='Sex', hue='Heart Disease', data=df)
plt.title('Distribusi Penyakit Jantung Berdasarkan Jenis Kelamin')
plt.xlabel('Jenis Kelamin (0 = Perempuan, 1 = Laki-laki)')
plt.ylabel('Jumlah Pasien')
plt.show()
pd.crosstab(df['Sex'], df['Heart Disease'], normalize='index')

"""##### **4.4. Kolesterol dan Penyakit Jantung**
Analisis ini mengkaji perbedaan kadar kolesterol
antara pasien dengan dan tanpa penyakit jantung.

"""

plt.figure(figsize=(8,5))
sns.boxplot(x='Heart Disease', y='Cholesterol', data=df)
plt.title('Distribusi Kolesterol Berdasarkan Penyakit Jantung')
plt.xlabel('Kondisi Penyakit Jantung')
plt.ylabel('Kolesterol')
plt.show()
df.groupby('Heart Disease')['Cholesterol'].mean()

"""##### **4.5. Tekanan Darah dan Penyakit Jantung**
Analisis ini membandingkan tekanan darah pasien
berdasarkan kondisi penyakit jantung.

"""

plt.figure(figsize=(8,5))
sns.boxplot(x='Heart Disease', y='BP', data=df)
plt.title('Distribusi Tekanan Darah Berdasarkan Penyakit Jantung')
plt.xlabel('Kondisi Penyakit Jantung')
plt.ylabel('Tekanan Darah')
plt.show()
df.groupby('Heart Disease')['BP'].mean()

"""##### **4.6. Detak Jantung Maksimum dan Penyakit Jantung**
Analisis ini menilai perbedaan kemampuan detak jantung maksimum
antara pasien dengan dan tanpa penyakit jantung.

"""

plt.figure(figsize=(8,5))
sns.boxplot(x='Heart Disease', y='Max HR', data=df)
plt.title('Distribusi Detak Jantung Maksimum Berdasarkan Penyakit Jantung')
plt.xlabel('Kondisi Penyakit Jantung')
plt.ylabel('Max Heart Rate')
plt.show()
df.groupby('Heart Disease')['Max HR'].mean()

"""### **Kesimpulan**
Berdasarkan hasil exploratory data analysis, ditemukan bahwa pasien
dengan penyakit jantung cenderung berusia lebih tua,
berjenis kelamin laki-laki, serta memiliki kadar kolesterol
dan tekanan darah yang lebih tinggi.

Perbedaan paling signifikan ditemukan pada variabel detak jantung maksimum (Max HR),
di mana pasien dengan penyakit jantung memiliki nilai yang lebih rendah
dibandingkan pasien tanpa penyakit jantung.
Hasil ini menunjukkan bahwa kombinasi faktor demografis dan klinis
berkaitan dengan risiko penyakit jantung.

"""

